### ISSUE TITLE
java.util.stream.IntStream;

### ISSUE THREAD

**Issue by JeffSkyrunner** [kyxap/google.challenge#1]
The java.util.stream.IntStream library is not permitted by Google:

/Answer.java:6: error: package java.util.stream does not exist
import java.util.stream.IntStream;
^
/Answer.java:6: error: package java.util.stream does not exist
import java.util.stream.IntStream;
^
/Answer.java:69: error: cannot find symbol
if (IntStream.of(m[row]).sum() == 0) {
^
symbol: variable IntStream
location: class com.google.challenges.Answer

**Comment by kyxap** [comment]
Is not clear about which part of code you talking about. 
Thanks
